MyChinook/MyChinook_Web/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using MyChinook_Web.Models.Dtos;
using MyChinook_Web.Models.Responses;
using MyChinook_Web.Services.IServices;
using Newtonsoft.Json;

namespace MyChinook_Web.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumService _albumService;

        public AlbumController(IAlbumService albumService)
        {
            _albumService = albumService;
        }

        public async Task<IActionResult> IndexAlbum()
        {
            List<AlbumDto> list = new();
            var response = await _albumService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<AlbumDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
    }
}

MyChinook/MyChinook_Web/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using MyChinook_Web.Models.Dtos;
using MyChinook_Web.Models.Responses;
using MyChinook_Web.Services.IServices;
using Newtonsoft.Json;
using System.Reflection;

namespace MyChinook_Web.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistService _artistService;

        public ArtistController(IArtistService artistService)
        {
            _artistService = artistService;
        }

        public async Task<IActionResult> IndexArtist()
        {
            List<ArtistDto> list = new();
            var response = await _artistService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ArtistDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public async Task<IActionResult> CreateArtist()
        {        
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateArtist(ArtistDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _artistService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexArtist));
                }
            }
            return View(model);
        }

        public async Task<IActionResult> UpdateArtist(int artistId)
        {   
            //recieve data after update
            var response = await _artistService.GetAsync<APIResponse>(artistId);
            if (response != null && response.IsSuccess)
            {
                ArtistDto model = JsonConvert.DeserializeObject<ArtistDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateArtist(ArtistDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _artistService.UpdateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexArtist));
                }
            }
            return View(model);
        }

        public async Task<IActionResult> DeleteArtist(int artistId)
        {
            //recieve data after update
            var response = await _artistService.GetAsync<APIResponse>(artistId);
            if (response != null && response.IsSuccess)
            {
                ArtistDto model = JsonConvert.DeserializeObject<ArtistDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteArtist(ArtistDto model)
        {
            var response = await _artistService.DeleteAsync<APIResponse>(model.ArtistId);
            if (response != null && response.IsSuccess)
            {                  
                return RedirectToAction(nameof(IndexArtist));       
            }
            return View(model);
        }
    }
}

MyChinook/MyChinook_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyChinook_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyChinook_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyChinook_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="IndexArtist">Artist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="IndexAlbum">Album</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2566 - MyChinook_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>